# This is a basic workflow to help you get started with Actions

name: Automated Metadata Signing

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 * * * *"
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  signing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Download pufed.key from GH Secrets
      - name: Download pufed.key
        env:
          PUFED_KEY : ${{secrets.PUFED_KEY}}
        run:
          echo "$PUFED_KEY" | base64 --decode > pufed.key
      - name: Sign the metadata
        uses: docker://docker.sunet.se/pyff:stable
        with:
          entrypoint: pyff
          args: /github/workspace/pufed.pyff
      - name: Commit
        uses: zwaldowski/git-commit-action@v1
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
